django_app/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from member.urls import apis as member_api_urls
from post.urls import apis as post_apis_urls
from post.urls import views as post_urls

api_urlpatterns = [
    url(r'^member/', include(member_api_urls)),
    url(r'^post/', include(post_apis_urls)),
]

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include(post_urls)),
    url(r'^api/', include(api_urlpatterns, namespace='api')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

django_app/member/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class MyUser(AbstractUser):
    """
    1. 팔로우, 차단을 함께 만들 수 있는 중간자 모델을 구현
        검색(django follower twitter model)

    2. MyUser의
        method:
            follow: 내가 누군가를 follow 하기
            block: 내가 누군가를 block 하기
        property:
            friends: 서로 follow하고 있는 관계
            followers: 나를 follow하고 있는 User들
            followings: 내가 follow하고 있는 User들
            block_users: 내가 block한 User들
    """

    relation = models.ManyToManyField(
        "self",
        symmetrical=False,
        related_name='relation_user_set',
        through='Relationship',
    )

    def follow(self, user):
        self.relations_from_user.create(
            to_user=user,
            relation_type=Relationship.TYPE_FOLLOW
        )

    def blocks(self, user):
        self.relations_from_user.create(
            to_user=user,
            relation_type=Relationship.TYPE_BLOCK
        )

    @property
    def following(self):
        relations = self.relations_from_user.filter(
            relation_type=Relationship.TYPE_FOLLOW
        )
        return MyUser.objects.filter(id__in=relations.values('to_user_id'))

    @property
    def followers(self):
        relations = self.relations_to_user.filter(
            relation_type=Relationship.TYPE_FOLLOW
        )
        return MyUser.objects.filter(id__in=relations.values('from_user_id'))

    @property
    def block_users(self):
        relations = self.relations_from_user.filter(
            relation_type=Relationship.TYPE_BLOCK
        )
        return MyUser.objects.filter(id__in=relations.values('to_user_id'))

    @property
    def friends(self):
        return self.following & self.followers


class Relationship(models.Model):
    TYPE_FOLLOW = 'f'
    TYPE_BLOCK = 'b'

    CHOICES_RELATION_TYPE = (
        (TYPE_FOLLOW, 'Follow'),
        (TYPE_BLOCK, 'Block'),
    )
    from_user = models.ForeignKey(MyUser, related_name='relations_from_user')
    to_user = models.ForeignKey(MyUser, related_name='relations_to_user')
    relation_type = models.CharField(max_length=1, choices=CHOICES_RELATION_TYPE)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Relation({}) From({}) To({})'.format(
            self.get_relation_type_display(),
            self.from_user.username,
            self.to_user.username,
        )

django_app/post/models/comment.py
from django.conf import settings
from django.db import models

from post.models.post import Post

__all__ = (
    'PostComment',
)


class PostComment(models.Model):
    post = models.ForeignKey(Post)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    content = models.TextField()

    def __str__(self):
        return '{} comment (author:{})'.format(
            self.post_id,
            self.author_id
        )

django_app/post/models/post.py
from django.conf import settings
from django.db import models

__all__ = (
    'Post',
    'PostPhoto',
)


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-pk',)


class PostPhoto(models.Model):
    post = models.ForeignKey(Post)
    photo = models.ImageField(upload_to='post')
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        order_with_respect_to = 'post'

django_app/post/forms.py
from django import forms


class PostForm(forms.Form):
    content = forms.CharField(required=False)
    photos = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={
                'multiple': True,
            }
        )
    )

django_app/member/views.py
from django.shortcuts import render

# Create your views here.

django_app/post/urls/views.py
from django.conf.urls import url

from .. import views

app_name = 'post'
urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='post-list'),
    url(r'^(?P<pk>[0-9]+)/$', views.PostDetail.as_view(), name='post-detail'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.PostDelete.as_view(), name='post-delete'),
    url(r'^create/$', views.PostCreate.as_view(), name='post-create'),

    url(r'^(?P<post_pk>[0-9]+)/comment/create/$',
        views.CommentCreate.as_view(),
        name='comment-create'),
]

django_app/post/views/comment.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView

from post.models import Post, PostComment

__all__ = (
    'CommentCreate',
)


@method_decorator(login_required, name='dispatch')
class CommentCreate(CreateView):
    """
    Comment Create가 동작할 수 있도록 urls및 이 뷰를 구현
    """
    model = PostComment
    fields = (
        'content',
    )

    def get_success_url(self):
        next = self.request.GET.get('next')
        return next if next else reverse('post:post-detail', kwargs={'pk': self.kwargs[
            'post_pk']})

    def form_valid(self, form):
        # author와 post가 빈 PostComment객체 생성
        comment = form.save(commit=False)
        post_pk = self.kwargs['post_pk']
        post = Post.objects.get(pk=post_pk)
        author = self.request.user
        comment.post = post
        comment.author = author
        comment.save()
        return HttpResponseRedirect(self.get_success_url())

django_app/post/views/post.py
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView
from django.views.generic.edit import FormView, DeleteView

from post.forms import PostForm
from post.models import Post, PostComment, PostPhoto

__all__ = (
    'PostList',
    'PostDetail',
    'PostCreate',
    'PostDelete',
)


class PostList(ListView):
    model = Post
    context_object_name = 'posts'


class PostDetail(DetailView):
    model = Post


class PostCreate(FormView):
    template_name = 'post/post_create.html'
    form_class = PostForm
    success_url = '/post/'

    def form_valid(self, form):
        post = Post.objects.create(author=self.request.user)
        content = form.cleaned_data.get('content', '').strip()
        if content != '':
            PostComment.objects.create(post=post, author=self.request.user, content=content)
        for file in self.request.FILES.getlist('photos'):
            PostPhoto.objects.create(post=post, photo=file)
        return super().form_valid(form)


class PostDelete(DeleteView):
    model = Post
    success_url = reverse_lazy('post:post-list')

django_app/templates/common/base.html
{% load staticfiles %}
<!doctype html>
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
	      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Instagram</title>
  <link rel="stylesheet" href="{% static 'css/sprites.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/common.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/header.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/post_list.min.css' %}">

	<!-- Swiper -->
	<link rel="stylesheet" href="{% static 'swiper/dist/css/swiper.min.css' %}">
</head>
<body>
  <div id="wrap">
    <div>
	    {{ user.username }}
    </div>
  	<header class="main-header">
  		<nav class="header-nav">
        <span class="nav-group nav-left">
          <a href="{% url 'post:post-list' %}" class="logo sprite-logo"></a>
        </span>

        <span class="nav-group nav-center">
          <input type="text">
        </span>

        <span class="nav-group nav-right">
          <a href="" class="btn-header-nav sprite-explore"></a>
          <a href="" class="btn-header-nav sprite-activity"></a>
          <a href="" class="btn-header-nav sprite-profile"></a>
        </span>
  		</nav>
  	</header>
    <div class="content-container">
    	{% block content %}
    	{% endblock %}
    </div>
  </div>
  <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'swiper/dist/js/swiper.min.js' %}"></script>
	{% block script %}
	{% endblock %}
</body>
</html>

django_app/templates/member/change_profile_image.html
{% extends 'common/base.html' %}

{% block content %}
<div>
    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{ form }}
        <button type="submit">바꾸기</button>
    </form>
</div>
{% endblock %}

django_app/templates/member/login.html
{% extends 'common/base.html' %}

{% block content %}

<h1>login</h1>
<form action="" method="POST">{% csrf_token %}
    {% if form.non_field_errors %}
        {{ form.non_field_errors }}
    {% endif %}

    {% for field in form %}
    <div>
        {{ field.label_tag }}
        {{ field }}
    </div>
    {% endfor %}
    <button type="submit">Login</button>
</form>

{% endblock %}

django_app/templates/member/profile.html
{% extends 'common/base.html' %}

{% block content %}
    <div class="profile-container">
        <div class="profile-top">
            <img src="" alt="" class="img-profile">
            <div class="profile-text">
                <div class="text-top">
                    <span class="profile-username">{{ user.username }}</span>
                    <a class="bth">프로필 편집</a>
                    <a href="{% url 'member:logout' %}" class="btn">Logout</a>
                </div>
                <div class="text-status">
                    <span class="status-item">게시물 {{ post_count }}개</span>
                    <span class="status-item">팔로워 {{ follower_count }}명</span>
                    <span class="status-item">팔로우 {{ following_count }}명</span>
                </div>
                <div class="text-name"></div>
            </div>
        </div>
    </div>
{% endblock %}

django_app/templates/member/signup.html
{% extends 'common/base.html' %}

{% block content %}
    <div class="signup_container">
        <form action="" method="POST">{% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
            <div>
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}
            <button type="submit">Signup</button>
        </form>
    </div>
{% endblock %}

django_app/templates/post/include/post.html
<article class="post">
  <header class="post-header">
    <span class="header-username">{{ post.author.username }}</span>
    <!-- Post delete form start -->
    {% if user == post.author %}
    <form action="{% url 'post:post-delete' pk=post.pk %}" method="POST" class="inline">{% csrf_token %}
      <button type="submit" class="btn">Delete</button>
    </form>
    {% endif %}
    <!-- Post delete form end -->
    <span class="header-date">{{ post.created_date }}</span>
  </header>

  <!--post내부에서 postphoto_set을 loop하며 postphoto.photo.url을 img의 src로 지정 -->
  <div class="post-image-container">

    <!-- Swiper container -->
    <div class="swiper-container">
	    <div class="swiper-wrapper">
				{% for postphoto in post.postphoto_set.all %}
		    <div class="swiper-slide">
			    <a href="{% url 'post:post-detail' pk=post.pk %}">
	          <img src="{{ postphoto.photo.url }}" alt="" class="post-image">
			    </a>
		    </div>
		    {% endfor %}
	    </div>
    </div>
    <!-- Swiper container end -->

  </div>


  <div class="post-bottom-container">
    <div class="post-content">{{ post.content|linebreaksbr|truncatechars:100 }}</div>
    <div class="post-like-users">
      {% if post.like_users.all %}
        {% for user in post.like_users.all %}
          <strong>{{ user.username }}</strong>
          {% if not forloop.last %}<strong>, </strong>{% endif %}
        {% endfor %}
        님이 좋아합니다.
      {% endif %}
    </div>
    <div class="post-comments">
      {% if post.postcomment_set.all %}
        {% for comment in post.postcomment_set.all %}
          <div class="post-comment">
            <span class="comment-author">{{ comment.author.username }}</span>
            <span class="comment-content">{{ comment.content }}</span>
            <!-- 삭제를 위한 Form -->
            {% if user == comment.author %}
            <form action="" method="POST">{% csrf_token %}
	            <button type="submit" class="btn">Delete</button>
            </form>
            {% endif %}
          </div>
        {% endfor %}
      {% endif %}
    </div>
    <div class="post-comment-form-container clearfix">
      <form action="" method="POST" class="form-like">{% csrf_token %}
	      <button
	        type="submit"
	        class="btn-like
	          {% if user in post.like_users.all %}
	            sprite-heart-full
	          {% else %}
	            sprite-heart-empty
	          {% endif %}">
	      </button>
      </form>

      <form action="{% url 'post:comment-create' post_pk=post.pk %}?next={{ request.path }}"
            method="POST"
            class="form-comment">{% csrf_token %}
        <input
          type="text"
          placeholder="댓글 달기..."
          class="input-comment"
          name="content">
      </form>
    </div>
  </div>
</article>

django_app/templates/post/post_add.html
{% extends 'common/base.html' %}

{% block content %}
	<div class="post-add-container">
		<form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
			{{ form }}
			<button type="submit">Upload</button>
		</form>
	</div>
{% endblock %}

django_app/templates/post/post_confirm_delete.html
{% extends 'common/base.html' %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>진짜 삭제? "{{ object }}"?</p>
</form>

django_app/templates/post/post_create.html
{% extends 'common/base.html' %}

{% block content %}
	<div class="post-add-container">
		<form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
			{{ form }}
			<button type="submit">Upload</button>
		</form>
	</div>
{% endblock %}

django_app/templates/post/post_detail.html
{% extends 'common/base.html' %}

{% block content %}
<div class="post-list-container">
{% include 'post/include/post.html' with post=post %}
</div>
{% endblock %}

{% block script %}
<script>
	$(document).ready(function () {
		new Swiper('.swiper-container');
	});
</script>
{% endblock %}

django_app/templates/post/post_list.html
{% extends 'common/base.html' %}

{% block content %}
<div class="post-list-container">
  {% for post in posts %}
		{% include 'post/include/post.html' with post=post %}
  {% endfor %}
	<a href="{% url 'post:post-create' %}" class="btn-add-post">+ Add Post</a>
</div>

{% endblock %}

{% block script %}
<script>
	$(document).ready(function () {
		new Swiper('.swiper-container');
	});
</script>
{% endblock %}

{#각 post에 연결된 Comment object list를 출력#}

django_app/templates/post/postcomment_form.html
<form action="" method="POST">{% csrf_token %}
	{{ form }}
	<button type="submit">Submit</button>
</form>